version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USERNAME: root
      MYSQL_PASSWORD:
      MYSQL_HOST: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/app/vendor/bundle
      - webpacker_cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
    stdin_open: true
    tty: true
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/app/vendor/bundle
      - webpacker_cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3035:3035"
volumes:
  mysql-data:
    driver: local
  node_modules:
  webpacker_cache:
  bundle:
